# Generated by Django 4.0.2 on 2022-02-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.FloatField(max_length=50, null=True)),
            ],
        ),
    ]
