# Generated by Django 3.2.11 on 2022-02-03 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expanse_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanse',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
